-- OneDayMore seed data
-- Compatible with the schema in onedaymore_mysql_schema.sql
-- Populates categories, products and discount_codes only.
-- orders and order_product are intentionally left empty because they are transactional data.

USE onedaymore;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE order_product;
TRUNCATE TABLE orders;
TRUNCATE TABLE discount_codes;
TRUNCATE TABLE products;
TRUNCATE TABLE categories;

SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO categories (id, name, slug, description) VALUES
(1, 'Pasti Liofilizzati', 'pasti-liofilizzati', 'Piatti completi liofilizzati per autonomia alimentare, leggeri e facili da preparare.'),
(2, 'Colazioni e Snack', 'colazioni-e-snack', 'Snack, barrette e colazioni ad alta resa energetica per emergenze e outdoor.'),
(3, 'Razioni ad Alta Densità Calorica', 'razioni-alta-densita-calorica', 'Razioni compatte e alimenti ad alto apporto calorico per kit di sopravvivenza.'),
(4, 'Bevande e Reintegro', 'bevande-e-reintegro', 'Bevande solubili, tè, caffè e mix per reintegro e preparazione rapida.');

INSERT INTO products (
    id, category_id, name, slug, short_description, description, brand, price,
    weight_grams, servings, calories, storage_life_months, preparation_type,
    water_needed_ml, quantity_available, is_active, image_url
) VALUES
(1, 1, 'Risotto ai Funghi Liofilizzato', 'risotto-ai-funghi-liofilizzato', 'Piatto pronto liofilizzato risotto ai funghi.', 'Pasto liofilizzato risotto ai funghi, pensato per emergenze, trekking e scorte di lunga durata.', 'TrailNest', '8.90', 105, 1, 450, 60, 'add_hot_water', 220, 72, 1, 'https://cdn.onedaymore.local/products/risotto-ai-funghi-liofilizzato.jpg'),
(2, 1, 'Pasta al Pomodoro Liofilizzato', 'pasta-al-pomodoro-liofilizzato', 'Piatto pronto liofilizzato pasta al pomodoro.', 'Pasto liofilizzato pasta al pomodoro, pensato per emergenze, trekking e scorte di lunga durata.', 'OrbitFuel', '8.90', 130, 2, 590, 72, 'add_hot_water', 200, 44, 1, 'https://cdn.onedaymore.local/products/pasta-al-pomodoro-liofilizzato.jpg'),
(3, 1, 'Cous Cous Mediterraneo Liofilizzato', 'cous-cous-mediterraneo-liofilizzato', 'Piatto pronto liofilizzato cous cous mediterraneo.', 'Pasto liofilizzato cous cous mediterraneo, pensato per emergenze, trekking e scorte di lunga durata.', 'NorthCamp', '11.40', 115, 1, 540, 72, 'add_hot_water', 300, 35, 1, 'https://cdn.onedaymore.local/products/cous-cous-mediterraneo-liofilizzato.jpg'),
(4, 1, 'Riso al Curry Liofilizzato', 'riso-al-curry-liofilizzato', 'Piatto pronto liofilizzato riso al curry.', 'Pasto liofilizzato riso al curry, pensato per emergenze, trekking e scorte di lunga durata.', 'TerraReady', '7.90', 135, 1, 590, 96, 'add_hot_water', 180, 69, 1, 'https://cdn.onedaymore.local/products/riso-al-curry-liofilizzato.jpg'),
(5, 1, 'Chili Vegetale Liofilizzato', 'chili-vegetale-liofilizzato', 'Piatto pronto liofilizzato chili vegetale.', 'Pasto liofilizzato chili vegetale, pensato per emergenze, trekking e scorte di lunga durata.', 'LastByte Foods', '9.20', 95, 1, 510, 84, 'add_hot_water', 250, 19, 1, 'https://cdn.onedaymore.local/products/chili-vegetale-liofilizzato.jpg'),
(6, 1, 'Zuppa di Lenticchie Liofilizzato', 'zuppa-di-lenticchie-liofilizzato', 'Piatto pronto liofilizzato zuppa di lenticchie.', 'Pasto liofilizzato zuppa di lenticchie, pensato per emergenze, trekking e scorte di lunga durata.', 'NorthCamp', '9.20', 135, 2, 480, 120, 'add_hot_water', 280, 44, 1, 'https://cdn.onedaymore.local/products/zuppa-di-lenticchie-liofilizzato.jpg'),
(7, 1, 'Polenta e Funghi Liofilizzato', 'polenta-e-funghi-liofilizzato', 'Piatto pronto liofilizzato polenta e funghi.', 'Pasto liofilizzato polenta e funghi, pensato per emergenze, trekking e scorte di lunga durata.', 'PeakShelf', '10.40', 115, 1, 590, 72, 'add_hot_water', 250, 30, 1, 'https://cdn.onedaymore.local/products/polenta-e-funghi-liofilizzato.jpg'),
(8, 1, 'Pasta e Fagioli Liofilizzato', 'pasta-e-fagioli-liofilizzato', 'Piatto pronto liofilizzato pasta e fagioli.', 'Pasto liofilizzato pasta e fagioli, pensato per emergenze, trekking e scorte di lunga durata.', 'LastByte Foods', '11.40', 135, 1, 590, 60, 'add_hot_water', 250, 84, 1, 'https://cdn.onedaymore.local/products/pasta-e-fagioli-liofilizzato.jpg'),
(9, 1, 'Riso e Verdure Liofilizzato', 'riso-e-verdure-liofilizzato', 'Piatto pronto liofilizzato riso e verdure.', 'Pasto liofilizzato riso e verdure, pensato per emergenze, trekking e scorte di lunga durata.', 'NorthCamp', '9.50', 95, 2, 540, 60, 'add_hot_water', 320, 63, 1, 'https://cdn.onedaymore.local/products/riso-e-verdure-liofilizzato.jpg'),
(10, 1, 'Spezzatino Vegetale Liofilizzato', 'spezzatino-vegetale-liofilizzato', 'Piatto pronto liofilizzato spezzatino vegetale.', 'Pasto liofilizzato spezzatino vegetale, pensato per emergenze, trekking e scorte di lunga durata.', 'PeakShelf', '10.40', 105, 2, 450, 120, 'add_hot_water', 300, 57, 1, 'https://cdn.onedaymore.local/products/spezzatino-vegetale-liofilizzato.jpg'),
(11, 1, 'Minestrone Proteico Liofilizzato', 'minestrone-proteico-liofilizzato', 'Piatto pronto liofilizzato minestrone proteico.', 'Pasto liofilizzato minestrone proteico, pensato per emergenze, trekking e scorte di lunga durata.', 'PrepHarvest', '10.40', 110, 2, 590, 120, 'add_hot_water', 180, 37, 1, 'https://cdn.onedaymore.local/products/minestrone-proteico-liofilizzato.jpg'),
(12, 1, 'Pasta al Pesto Liofilizzato', 'pasta-al-pesto-liofilizzato', 'Piatto pronto liofilizzato pasta al pesto.', 'Pasto liofilizzato pasta al pesto, pensato per emergenze, trekking e scorte di lunga durata.', 'TerraReady', '8.90', 105, 1, 560, 120, 'add_hot_water', 200, 71, 1, 'https://cdn.onedaymore.local/products/pasta-al-pesto-liofilizzato.jpg'),
(13, 1, 'Riso Tex-Mex Liofilizzato', 'riso-tex-mex-liofilizzato', 'Piatto pronto liofilizzato riso tex-mex.', 'Pasto liofilizzato riso tex-mex, pensato per emergenze, trekking e scorte di lunga durata.', 'PrepHarvest', '10.90', 105, 1, 560, 120, 'add_hot_water', 250, 50, 1, 'https://cdn.onedaymore.local/products/riso-tex-mex-liofilizzato.jpg'),
(14, 1, 'Patate e Porri Liofilizzato', 'patate-e-porri-liofilizzato', 'Piatto pronto liofilizzato patate e porri.', 'Pasto liofilizzato patate e porri, pensato per emergenze, trekking e scorte di lunga durata.', 'PrepHarvest', '10.40', 115, 2, 510, 84, 'add_hot_water', 220, 50, 1, 'https://cdn.onedaymore.local/products/patate-e-porri-liofilizzato.jpg'),
(15, 1, 'Orzo e Legumi Liofilizzato', 'orzo-e-legumi-liofilizzato', 'Piatto pronto liofilizzato orzo e legumi.', 'Pasto liofilizzato orzo e legumi, pensato per emergenze, trekking e scorte di lunga durata.', 'TerraReady', '8.40', 120, 1, 420, 60, 'add_hot_water', 200, 37, 1, 'https://cdn.onedaymore.local/products/orzo-e-legumi-liofilizzato.jpg'),
(16, 1, 'Paella Vegetale Liofilizzato', 'paella-vegetale-liofilizzato', 'Piatto pronto liofilizzato paella vegetale.', 'Pasto liofilizzato paella vegetale, pensato per emergenze, trekking e scorte di lunga durata.', 'NorthCamp', '8.90', 105, 1, 540, 84, 'add_hot_water', 320, 68, 1, 'https://cdn.onedaymore.local/products/paella-vegetale-liofilizzato.jpg'),
(17, 1, 'Pasta alla Norma Liofilizzato', 'pasta-alla-norma-liofilizzato', 'Piatto pronto liofilizzato pasta alla norma.', 'Pasto liofilizzato pasta alla norma, pensato per emergenze, trekking e scorte di lunga durata.', 'SafePantry', '8.40', 115, 1, 620, 84, 'add_hot_water', 320, 23, 1, 'https://cdn.onedaymore.local/products/pasta-alla-norma-liofilizzato.jpg'),
(18, 1, 'Riso Thai Piccante Liofilizzato', 'riso-thai-piccante-liofilizzato', 'Piatto pronto liofilizzato riso thai piccante.', 'Pasto liofilizzato riso thai piccante, pensato per emergenze, trekking e scorte di lunga durata.', 'NorthCamp', '9.50', 105, 2, 560, 72, 'add_hot_water', 320, 74, 1, 'https://cdn.onedaymore.local/products/riso-thai-piccante-liofilizzato.jpg'),
(19, 1, 'Zuppa di Ceci Liofilizzato', 'zuppa-di-ceci-liofilizzato', 'Piatto pronto liofilizzato zuppa di ceci.', 'Pasto liofilizzato zuppa di ceci, pensato per emergenze, trekking e scorte di lunga durata.', 'NorthCamp', '10.40', 110, 1, 620, 84, 'add_hot_water', 280, 37, 1, 'https://cdn.onedaymore.local/products/zuppa-di-ceci-liofilizzato.jpg'),
(20, 1, 'Gnocchi al Formaggio Liofilizzato', 'gnocchi-al-formaggio-liofilizzato', 'Piatto pronto liofilizzato gnocchi al formaggio.', 'Pasto liofilizzato gnocchi al formaggio, pensato per emergenze, trekking e scorte di lunga durata.', 'NorthCamp', '10.90', 115, 1, 420, 60, 'add_hot_water', 200, 65, 1, 'https://cdn.onedaymore.local/products/gnocchi-al-formaggio-liofilizzato.jpg'),
(21, 2, 'Porridge Mela e Cannella', 'porridge-mela-e-cannella', 'Snack o colazione porridge mela e cannella.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: porridge mela e cannella.', 'TrailNest', '5.90', 70, 1, 320, 24, 'ready_to_eat', NULL, 27, 1, 'https://cdn.onedaymore.local/products/porridge-mela-e-cannella.jpg'),
(22, 2, 'Granola al Cacao', 'granola-al-cacao', 'Snack o colazione granola al cacao.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: granola al cacao.', 'TerraReady', '3.90', 55, 2, 320, 48, 'add_cold_water', 220, 89, 1, 'https://cdn.onedaymore.local/products/granola-al-cacao.jpg'),
(23, 2, 'Muesli Frutti Rossi', 'muesli-frutti-rossi', 'Snack o colazione muesli frutti rossi.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: muesli frutti rossi.', 'OrbitFuel', '4.90', 80, 1, 280, 48, 'ready_to_eat', NULL, 73, 1, 'https://cdn.onedaymore.local/products/muesli-frutti-rossi.jpg'),
(24, 2, 'Barretta Avena e Miele', 'barretta-avena-e-miele', 'Snack o colazione barretta avena e miele.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: barretta avena e miele.', 'TrailNest', '4.90', 60, 1, 380, 36, 'add_cold_water', 200, 63, 1, 'https://cdn.onedaymore.local/products/barretta-avena-e-miele.jpg'),
(25, 2, 'Barretta Cacao e Nocciole', 'barretta-cacao-e-nocciole', 'Snack o colazione barretta cacao e nocciole.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: barretta cacao e nocciole.', 'PrepHarvest', '3.90', 50, 1, 320, 72, 'ready_to_eat', NULL, 103, 1, 'https://cdn.onedaymore.local/products/barretta-cacao-e-nocciole.jpg'),
(26, 2, 'Crackers Proteici', 'crackers-proteici', 'Snack o colazione crackers proteici.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: crackers proteici.', 'TerraReady', '6.90', 80, 1, 300, 60, 'add_hot_water', 180, 39, 1, 'https://cdn.onedaymore.local/products/crackers-proteici.jpg'),
(27, 2, 'Biscotti Energetici', 'biscotti-energetici', 'Snack o colazione biscotti energetici.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: biscotti energetici.', 'SafePantry', '5.50', 60, 1, 230, 48, 'add_cold_water', 150, 96, 1, 'https://cdn.onedaymore.local/products/biscotti-energetici.jpg'),
(28, 2, 'Mix Frutta Secca', 'mix-frutta-secca', 'Snack o colazione mix frutta secca.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: mix frutta secca.', 'SafePantry', '4.20', 60, 1, 250, 72, 'add_cold_water', 200, 62, 1, 'https://cdn.onedaymore.local/products/mix-frutta-secca.jpg'),
(29, 2, 'Chips di Banana', 'chips-di-banana', 'Snack o colazione chips di banana.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: chips di banana.', 'NorthCamp', '5.90', 55, 1, 320, 48, 'add_cold_water', 120, 65, 1, 'https://cdn.onedaymore.local/products/chips-di-banana.jpg'),
(30, 2, 'Snack Croccante ai Ceci', 'snack-croccante-ai-ceci', 'Snack o colazione snack croccante ai ceci.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: snack croccante ai ceci.', 'LastByte Foods', '5.50', 45, 3, 380, 72, 'add_cold_water', 220, 114, 1, 'https://cdn.onedaymore.local/products/snack-croccante-ai-ceci.jpg'),
(31, 2, 'Crema di Riso Vaniglia', 'crema-di-riso-vaniglia', 'Snack o colazione crema di riso vaniglia.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: crema di riso vaniglia.', 'PeakShelf', '5.20', 80, 1, 350, 36, 'ready_to_eat', NULL, 103, 1, 'https://cdn.onedaymore.local/products/crema-di-riso-vaniglia.jpg'),
(32, 2, 'Colazione Proteica Cocco', 'colazione-proteica-cocco', 'Snack o colazione colazione proteica cocco.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: colazione proteica cocco.', 'PrepHarvest', '5.90', 75, 1, 320, 72, 'add_hot_water', 180, 59, 1, 'https://cdn.onedaymore.local/products/colazione-proteica-cocco.jpg'),
(33, 2, 'Porridge Banana e Cacao', 'porridge-banana-e-cacao', 'Snack o colazione porridge banana e cacao.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: porridge banana e cacao.', 'TrailNest', '6.40', 90, 1, 350, 48, 'ready_to_eat', NULL, 60, 1, 'https://cdn.onedaymore.local/products/porridge-banana-e-cacao.jpg'),
(34, 2, 'Barretta Datteri e Mandorle', 'barretta-datteri-e-mandorle', 'Snack o colazione barretta datteri e mandorle.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: barretta datteri e mandorle.', 'OrbitFuel', '5.90', 45, 1, 350, 60, 'add_cold_water', 220, 61, 1, 'https://cdn.onedaymore.local/products/barretta-datteri-e-mandorle.jpg'),
(35, 2, 'Muesli Tropicale', 'muesli-tropicale', 'Snack o colazione muesli tropicale.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: muesli tropicale.', 'LastByte Foods', '5.50', 80, 2, 250, 24, 'add_hot_water', 220, 56, 1, 'https://cdn.onedaymore.local/products/muesli-tropicale.jpg'),
(36, 2, 'Snack Mais e Formaggio', 'snack-mais-e-formaggio', 'Snack o colazione snack mais e formaggio.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: snack mais e formaggio.', 'TrailNest', '6.40', 60, 3, 230, 60, 'add_cold_water', 200, 77, 1, 'https://cdn.onedaymore.local/products/snack-mais-e-formaggio.jpg'),
(37, 2, 'Brownie Energetico', 'brownie-energetico', 'Snack o colazione brownie energetico.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: brownie energetico.', 'LastByte Foods', '5.50', 90, 3, 380, 24, 'ready_to_eat', NULL, 82, 1, 'https://cdn.onedaymore.local/products/brownie-energetico.jpg'),
(38, 2, 'Biscotti Integrali', 'biscotti-integrali', 'Snack o colazione biscotti integrali.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: biscotti integrali.', 'PrepHarvest', '4.20', 70, 2, 180, 36, 'add_hot_water', 200, 23, 1, 'https://cdn.onedaymore.local/products/biscotti-integrali.jpg'),
(39, 2, 'Granola Caffè', 'granola-caffe', 'Snack o colazione granola caffè.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: granola caffè.', 'SafePantry', '3.90', 55, 1, 210, 60, 'add_hot_water', 180, 39, 1, 'https://cdn.onedaymore.local/products/granola-caffe.jpg'),
(40, 2, 'Barretta Salata Arachidi', 'barretta-salata-arachidi', 'Snack o colazione barretta salata arachidi.', 'Prodotto ideale per colazioni rapide, kit emergenza e attività outdoor: barretta salata arachidi.', 'LastByte Foods', '4.20', 50, 3, 250, 72, 'add_cold_water', 150, 62, 1, 'https://cdn.onedaymore.local/products/barretta-salata-arachidi.jpg'),
(41, 3, 'Razione 1200 kcal Classica', 'razione-1200-kcal-classica', 'Razione compatta razione 1200 kcal classica.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: razione 1200 kcal classica.', 'PeakShelf', '19.90', 125, 6, 500, 240, 'ready_to_eat', NULL, 35, 1, 'https://cdn.onedaymore.local/products/razione-1200-kcal-classica.jpg'),
(42, 3, 'Razione 1200 kcal Cacao', 'razione-1200-kcal-cacao', 'Razione compatta razione 1200 kcal cacao.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: razione 1200 kcal cacao.', 'PrepHarvest', '19.90', 300, 1, 800, 60, 'add_cold_water', 200, 52, 1, 'https://cdn.onedaymore.local/products/razione-1200-kcal-cacao.jpg'),
(43, 3, 'Razione 2400 kcal Survival', 'razione-2400-kcal-survival', 'Razione compatta razione 2400 kcal survival.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: razione 2400 kcal survival.', 'LastByte Foods', '6.90', 400, 3, 500, 60, 'ready_to_eat', NULL, 31, 1, 'https://cdn.onedaymore.local/products/razione-2400-kcal-survival.jpg'),
(44, 3, 'Razione 2400 kcal Arancia', 'razione-2400-kcal-arancia', 'Razione compatta razione 2400 kcal arancia.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: razione 2400 kcal arancia.', 'PrepHarvest', '13.90', 1200, 1, 900, 60, 'ready_to_eat', NULL, 55, 1, 'https://cdn.onedaymore.local/products/razione-2400-kcal-arancia.jpg'),
(45, 3, 'Razione 3600 kcal Family Pack', 'razione-3600-kcal-family-pack', 'Razione compatta razione 3600 kcal family pack.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: razione 3600 kcal family pack.', 'PeakShelf', '6.90', 250, 6, 500, 72, 'ready_to_eat', NULL, 35, 1, 'https://cdn.onedaymore.local/products/razione-3600-kcal-family-pack.jpg'),
(46, 3, 'Biscotti d''Emergenza 12h', 'biscotti-demergenza-12h', 'Razione compatta biscotti d''emergenza 12h.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: biscotti d''emergenza 12h.', 'TerraReady', '6.90', 300, 4, 3600, 96, 'ready_to_eat', NULL, 38, 1, 'https://cdn.onedaymore.local/products/biscotti-demergenza-12h.jpg'),
(47, 3, 'Barra Compatta 500 kcal', 'barra-compatta-500-kcal', 'Razione compatta barra compatta 500 kcal.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: barra compatta 500 kcal.', 'NorthCamp', '8.90', 800, 1, 2400, 84, 'ready_to_eat', NULL, 54, 1, 'https://cdn.onedaymore.local/products/barra-compatta-500-kcal.jpg'),
(48, 3, 'Barra Compatta 800 kcal', 'barra-compatta-800-kcal', 'Razione compatta barra compatta 800 kcal.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: barra compatta 800 kcal.', 'PeakShelf', '6.90', 650, 4, 1200, 96, 'ready_to_eat', NULL, 27, 1, 'https://cdn.onedaymore.local/products/barra-compatta-800-kcal.jpg'),
(49, 3, 'Kit Razione 24 Ore Base', 'kit-razione-24-ore-base', 'Razione compatta kit razione 24 ore base.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: kit razione 24 ore base.', 'PeakShelf', '13.90', 250, 3, 2400, 180, 'ready_to_eat', NULL, 26, 1, 'https://cdn.onedaymore.local/products/kit-razione-24-ore-base.jpg'),
(50, 3, 'Kit Razione 24 Ore Pro', 'kit-razione-24-ore-pro', 'Razione compatta kit razione 24 ore pro.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: kit razione 24 ore pro.', 'PrepHarvest', '6.90', 500, 4, 1800, 180, 'ready_to_eat', NULL, 63, 1, 'https://cdn.onedaymore.local/products/kit-razione-24-ore-pro.jpg'),
(51, 3, 'Razione Nautica 2400 kcal', 'razione-nautica-2400-kcal', 'Razione compatta razione nautica 2400 kcal.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: razione nautica 2400 kcal.', 'PrepHarvest', '13.90', 100, 2, 800, 72, 'ready_to_eat', NULL, 19, 1, 'https://cdn.onedaymore.local/products/razione-nautica-2400-kcal.jpg'),
(52, 3, 'Razione Montagna 2400 kcal', 'razione-montagna-2400-kcal', 'Razione compatta razione montagna 2400 kcal.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: razione montagna 2400 kcal.', 'OrbitFuel', '15.90', 125, 1, 900, 60, 'ready_to_eat', NULL, 20, 1, 'https://cdn.onedaymore.local/products/razione-montagna-2400-kcal.jpg'),
(53, 3, 'Blocco Energetico Miele', 'blocco-energetico-miele', 'Razione compatta blocco energetico miele.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: blocco energetico miele.', 'NorthCamp', '7.90', 250, 4, 1200, 60, 'add_cold_water', 150, 53, 1, 'https://cdn.onedaymore.local/products/blocco-energetico-miele.jpg'),
(54, 3, 'Blocco Energetico Cacao', 'blocco-energetico-cacao', 'Razione compatta blocco energetico cacao.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: blocco energetico cacao.', 'PeakShelf', '29.90', 500, 2, 500, 72, 'ready_to_eat', NULL, 45, 1, 'https://cdn.onedaymore.local/products/blocco-energetico-cacao.jpg'),
(55, 3, 'Emergency Meal Brick', 'emergency-meal-brick', 'Razione compatta emergency meal brick.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: emergency meal brick.', 'NorthCamp', '8.90', 200, 1, 800, 60, 'ready_to_eat', NULL, 19, 1, 'https://cdn.onedaymore.local/products/emergency-meal-brick.jpg'),
(56, 3, 'Razione Tropicale 2400 kcal', 'razione-tropicale-2400-kcal', 'Razione compatta razione tropicale 2400 kcal.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: razione tropicale 2400 kcal.', 'NorthCamp', '15.90', 800, 4, 800, 84, 'ready_to_eat', NULL, 31, 1, 'https://cdn.onedaymore.local/products/razione-tropicale-2400-kcal.jpg'),
(57, 3, 'Razione Invernale 2400 kcal', 'razione-invernale-2400-kcal', 'Razione compatta razione invernale 2400 kcal.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: razione invernale 2400 kcal.', 'OrbitFuel', '17.90', 300, 3, 1200, 96, 'add_cold_water', 500, 29, 1, 'https://cdn.onedaymore.local/products/razione-invernale-2400-kcal.jpg'),
(58, 3, 'Razione Tascabile 900 kcal', 'razione-tascabile-900-kcal', 'Razione compatta razione tascabile 900 kcal.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: razione tascabile 900 kcal.', 'LastByte Foods', '29.90', 650, 4, 3600, 180, 'add_cold_water', 300, 29, 1, 'https://cdn.onedaymore.local/products/razione-tascabile-900-kcal.jpg'),
(59, 3, 'Pack Alta Energia 1800 kcal', 'pack-alta-energia-1800-kcal', 'Razione compatta pack alta energia 1800 kcal.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: pack alta energia 1800 kcal.', 'PeakShelf', '19.90', 200, 6, 500, 120, 'ready_to_eat', NULL, 29, 1, 'https://cdn.onedaymore.local/products/pack-alta-energia-1800-kcal.jpg'),
(60, 3, 'Kit Blackout 72h Food Base', 'kit-blackout-72h-food-base', 'Razione compatta kit blackout 72h food base.', 'Razione ad alta densità calorica per emergenze e kit di autonomia: kit blackout 72h food base.', 'LastByte Foods', '6.90', 200, 1, 900, 180, 'add_cold_water', 500, 55, 1, 'https://cdn.onedaymore.local/products/kit-blackout-72h-food-base.jpg'),
(61, 4, 'Caffè Solubile Strong', 'caffe-solubile-strong', 'Bevanda o preparato caffè solubile strong.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: caffè solubile strong.', 'SafePantry', '3.20', 30, 5, 80, 60, 'add_hot_water', 150, 66, 1, 'https://cdn.onedaymore.local/products/caffe-solubile-strong.jpg'),
(62, 4, 'Tè Nero Solubile', 'te-nero-solubile', 'Bevanda o preparato tè nero solubile.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: tè nero solubile.', 'PeakShelf', '3.50', 200, 5, 60, 72, 'add_cold_water', 250, 64, 1, 'https://cdn.onedaymore.local/products/te-nero-solubile.jpg'),
(63, 4, 'Tisana Zenzero e Limone', 'tisana-zenzero-e-limone', 'Bevanda o preparato tisana zenzero e limone.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: tisana zenzero e limone.', 'LastByte Foods', '3.20', 120, 8, 150, 84, 'add_cold_water', 250, 22, 1, 'https://cdn.onedaymore.local/products/tisana-zenzero-e-limone.jpg'),
(64, 4, 'Cacao Istantaneo', 'cacao-istantaneo', 'Bevanda o preparato cacao istantaneo.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: cacao istantaneo.', 'SafePantry', '3.90', 200, 5, 80, 84, 'add_hot_water', 200, 28, 1, 'https://cdn.onedaymore.local/products/cacao-istantaneo.jpg'),
(65, 4, 'Bevanda Isotonica Agrumi', 'bevanda-isotonica-agrumi', 'Bevanda o preparato bevanda isotonica agrumi.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: bevanda isotonica agrumi.', 'OrbitFuel', '2.90', 40, 8, 150, 84, 'add_cold_water', 220, 102, 1, 'https://cdn.onedaymore.local/products/bevanda-isotonica-agrumi.jpg'),
(66, 4, 'Bevanda Isotonica Frutti Rossi', 'bevanda-isotonica-frutti-rossi', 'Bevanda o preparato bevanda isotonica frutti rossi.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: bevanda isotonica frutti rossi.', 'PrepHarvest', '3.20', 30, 5, 220, 48, 'add_hot_water', 300, 20, 1, 'https://cdn.onedaymore.local/products/bevanda-isotonica-frutti-rossi.jpg'),
(67, 4, 'Brodo Vegetale Solubile', 'brodo-vegetale-solubile', 'Bevanda o preparato brodo vegetale solubile.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: brodo vegetale solubile.', 'OrbitFuel', '5.50', 300, 12, 40, 36, 'add_cold_water', 200, 109, 1, 'https://cdn.onedaymore.local/products/brodo-vegetale-solubile.jpg'),
(68, 4, 'Latte in Polvere Intero', 'latte-in-polvere-intero', 'Bevanda o preparato latte in polvere intero.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: latte in polvere intero.', 'LastByte Foods', '4.90', 40, 10, 80, 48, 'add_cold_water', 250, 21, 1, 'https://cdn.onedaymore.local/products/latte-in-polvere-intero.jpg'),
(69, 4, 'Latte in Polvere Scremato', 'latte-in-polvere-scremato', 'Bevanda o preparato latte in polvere scremato.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: latte in polvere scremato.', 'TerraReady', '2.90', 40, 6, 180, 48, 'add_hot_water', 250, 92, 1, 'https://cdn.onedaymore.local/products/latte-in-polvere-scremato.jpg'),
(70, 4, 'Preparato Cappuccino', 'preparato-cappuccino', 'Bevanda o preparato preparato cappuccino.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: preparato cappuccino.', 'OrbitFuel', '3.20', 150, 5, 80, 48, 'add_hot_water', 180, 41, 1, 'https://cdn.onedaymore.local/products/preparato-cappuccino.jpg'),
(71, 4, 'Preparato Cioccolata Calda', 'preparato-cioccolata-calda', 'Bevanda o preparato preparato cioccolata calda.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: preparato cioccolata calda.', 'PeakShelf', '4.50', 80, 10, 60, 24, 'add_cold_water', 250, 97, 1, 'https://cdn.onedaymore.local/products/preparato-cioccolata-calda.jpg'),
(72, 4, 'Infuso Relax', 'infuso-relax', 'Bevanda o preparato infuso relax.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: infuso relax.', 'OrbitFuel', '2.90', 60, 4, 60, 36, 'add_cold_water', 250, 93, 1, 'https://cdn.onedaymore.local/products/infuso-relax.jpg'),
(73, 4, 'Energia in Polvere Ginseng', 'energia-in-polvere-ginseng', 'Bevanda o preparato energia in polvere ginseng.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: energia in polvere ginseng.', 'TerraReady', '3.90', 100, 4, 220, 36, 'add_hot_water', 300, 67, 1, 'https://cdn.onedaymore.local/products/energia-in-polvere-ginseng.jpg'),
(74, 4, 'Bevanda Elettroliti Neutra', 'bevanda-elettroliti-neutra', 'Bevanda o preparato bevanda elettroliti neutra.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: bevanda elettroliti neutra.', 'NorthCamp', '6.50', 60, 8, 40, 36, 'add_hot_water', 150, 41, 1, 'https://cdn.onedaymore.local/products/bevanda-elettroliti-neutra.jpg'),
(75, 4, 'Succo Liofilizzato Arancia', 'succo-liofilizzato-arancia', 'Bevanda o preparato succo liofilizzato arancia.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: succo liofilizzato arancia.', 'OrbitFuel', '4.20', 200, 6, 150, 48, 'add_cold_water', 180, 97, 1, 'https://cdn.onedaymore.local/products/succo-liofilizzato-arancia.jpg'),
(76, 4, 'Succo Liofilizzato Mela', 'succo-liofilizzato-mela', 'Bevanda o preparato succo liofilizzato mela.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: succo liofilizzato mela.', 'PrepHarvest', '5.90', 200, 10, 100, 36, 'add_cold_water', 220, 81, 1, 'https://cdn.onedaymore.local/products/succo-liofilizzato-mela.jpg'),
(77, 4, 'Protein Drink Vaniglia', 'protein-drink-vaniglia', 'Bevanda o preparato protein drink vaniglia.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: protein drink vaniglia.', 'PrepHarvest', '2.90', 60, 8, 80, 60, 'add_cold_water', 300, 86, 1, 'https://cdn.onedaymore.local/products/protein-drink-vaniglia.jpg'),
(78, 4, 'Protein Drink Cacao', 'protein-drink-cacao', 'Bevanda o preparato protein drink cacao.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: protein drink cacao.', 'LastByte Foods', '4.50', 100, 12, 100, 60, 'add_cold_water', 300, 70, 1, 'https://cdn.onedaymore.local/products/protein-drink-cacao.jpg'),
(79, 4, 'Tè Verde Solubile', 'te-verde-solubile', 'Bevanda o preparato tè verde solubile.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: tè verde solubile.', 'SafePantry', '4.90', 40, 8, 120, 60, 'add_hot_water', 200, 61, 1, 'https://cdn.onedaymore.local/products/te-verde-solubile.jpg'),
(80, 4, 'Preparato Zuppa Istantanea', 'preparato-zuppa-istantanea', 'Bevanda o preparato preparato zuppa istantanea.', 'Preparato pratico da dispensa per emergenze, reintegro o bevande calde/fredde: preparato zuppa istantanea.', 'OrbitFuel', '4.90', 40, 5, 180, 48, 'add_hot_water', 180, 71, 1, 'https://cdn.onedaymore.local/products/preparato-zuppa-istantanea.jpg');

INSERT INTO discount_codes (
    id, code, description, discount_type, discount_value, min_order_amount,
    starts_at, ends_at, is_active
) VALUES
(1, 'LAUNCH10', 'Sconto lancio 10% per il periodo di presentazione del progetto.', 'percentage', 10.00, 39.00, '2026-04-01 00:00:00', '2026-04-30 23:59:59', 1),
(2, 'APRILE6', 'Sconto fisso di 6 euro per carrelli medi durante la presentazione.', 'fixed', 6.00, 59.00, '2026-04-10 00:00:00', '2026-05-09 23:59:59', 1),
(3, 'SUMMER12', 'Promo estiva 12% su carrelli più ricchi, ideale per bundle e kit.', 'percentage', 12.00, 69.00, '2026-07-01 00:00:00', '2026-07-31 23:59:59', 1),
(4, 'BLACK15', 'Sconto fisso autunnale per ordini grandi e kit famiglia.', 'fixed', 15.00, 99.00, '2026-11-01 00:00:00', '2026-11-30 23:59:59', 1),
(5, 'SPRING8', 'Promo pre-stagione outdoor con sconto percentuale moderato.', 'percentage', 8.00, 49.00, '2027-03-15 00:00:00', '2027-04-14 23:59:59', 1);
