INSERT INTO products (
  category_id,
  name,
  slug,
  short_description,
  description,
  brand,
  price,
  weight_grams,
  servings,
  calories,
  storage_life_months,
  preparation_type,
  water_needed_ml,
  quantity_available,
  is_active,
  image_url
) VALUES 

(
  4,
  'Scorta d''acqua potabile 5L',
  'scorta-acqua-potabile-5l',
  'Contenitore compatto da 5 litri di acqua potabile a lunga conservazione.',
  'Scorta d''acqua potabile da 5 litri, ideale per emergenze domestiche o outdoor. Pronta all''uso, non richiede preparazione. Formato compatto facile da trasportare.',
  'SafeWater',
  6.90,
  5000,
  10,
  0,
  60,
  'ready_to_drink',
  NULL,
  80,
  1,
  'https://cdn.onedaymore.local/products/scorta-acqua-potabile-5l.jpg'
),

(
  4,
  'Scorta d''acqua potabile 10L',
  'scorta-acqua-potabile-10l',
  'Contenitore da 10 litri di acqua potabile a lunga conservazione.',
  'Scorta d''acqua potabile da 10 litri confezionata in contenitore resistente. Ideale per kit di emergenza domestici e blackout. Pronta all''uso.',
  'SafeWater',
  12.90,
  10000,
  20,
  0,
  60,
  'ready_to_drink',
  NULL,
  60,
  1,
  'https://cdn.onedaymore.local/products/scorta-acqua-potabile-10l.jpg'
),

(
  4,
  'Scorta d''acqua potabile 20L',
  'scorta-acqua-potabile-20l',
  'Contenitore da 20 litri di acqua potabile per autonomia prolungata.',
  'Scorta d''acqua potabile da 20 litri pensata per garantire autonomia in situazioni di emergenza prolungata. Perfetta per famiglie o gruppi.',
  'SafeWater',
  22.90,
  20000,
  40,
  0,
  60,
  'ready_to_drink',
  NULL,
  40,
  1,
  'https://cdn.onedaymore.local/products/scorta-acqua-potabile-20l.jpg'
);